Repository twitter/twurl, pull requests merged in 2019-12, with the labels that each got.

#119 [bug fix] Stop manual URI parsing/escaping and use CGI::parse
  .travis.yml
  lib/twurl/cli.rb
  lib/twurl/oauth_client.rb
  twurl.gemspec
Labels: BugFix

#125 make username option settable on requests
  lib/twurl/oauth_client.rb
  test/cli_test.rb
  test/oauth_client_test.rb
  test/rcfile_test.rb
Labels: Enhancement

#110 Use IO.binread instead of IO.read
  lib/twurl/oauth_client.rb
Labels: BugFix

#111 Fix PIN authorization
  lib/twurl/oauth_client.rb
  twurl.gemspec
Labels: BugFix

#126 Add twurl version to user agent header
  lib/twurl/oauth_client.rb
  test/oauth_client_test.rb
Labels: Enhancement

#128 Add --timeout and --connection-timeout options
  lib/twurl/cli.rb
  lib/twurl/oauth_client.rb
  test/account_information_controller_test.rb
  test/cli_test.rb
Labels: Enhancement

#114 Make aliases work again Closes: #93
  lib/twurl/cli.rb
Labels: BugFix

#129 Release v0.9.4
  lib/twurl/request_controller.rb
  lib/twurl/version.rb
  twurl.gemspec
Labels: Enhancement

#131 Support authorization options on request
  lib/twurl/oauth_client.rb
  test/oauth_client_test.rb
Labels: Enhancement

#130 Add -j (--json-pretty) option
  .gitignore
  INSTALL
  INSTALL.md
  lib/twurl.rb
  lib/twurl/cli.rb
  lib/twurl/request_controller.rb
  test/request_controller_test.rb
  test/test_helper.rb
  twurl.gemspec
Labels: Enhancement

#133 Documentation improvements
  .gitignore
  CONTRIBUTING.md
  README.md
  twurl.gemspec
Labels: Trivial

#132 Support Bearer Token
  README.md
  lib/twurl/app_only_oauth_client.rb
  lib/twurl/app_only_token_information_controller.rb
  lib/twurl/cli.rb
  lib/twurl/oauth_client.rb
  lib/twurl/rcfile.rb
  lib/twurl/request_controller.rb
  test/app_only_oauth_client_test.rb
  test/authorization_controller_test.rb
  test/cli_test.rb
  test/oauth_client_test.rb
  test/rcfile_test.rb
  test/request_controller_test.rb
  test/test_helper.rb
Labels: Enhancement

#136 Fix .gemspec
  twurl.gemspec
Labels: BugFix

#137 Add Ruby 2.7.0 to .travis.yml
  .travis.yml
  CONTRIBUTING.md
Labels: Trivial

#138 Add VSCode remote container setting files
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  twurl.gemspec
Labels: Trivial
